name: Master Unit + Integration
        on:
          push:
            branches: [ main ]
        jobs:
          ping:
            runs-on: ubuntu-latest
            steps:
              - run: echo "hello from main"
