name: PR Unit Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity check
        run: |
          ls -R
          python - <<'PY'
import os, sys
print("CWD:", os.getcwd())
print("src exists:", os.path.exists("src"))
print("calc exists:", os.path.exists("src/calc.py"))
print("PYTHONPATH will be set to src in next step")
PY

      - name: Run unit tests
        env:
          PYTHONPATH: src
        run: pytest tests/unit -q
