name: PR Unit Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Debug env
        run: |
          pwd
          ls -R
          echo "pytest.ini:"; cat pytest.ini || true
          python - <<'PY'
import sys, os
print("CWD:", os.getcwd())
print("sys.path:", sys.path)
print("src/calc.py exists:", os.path.exists("src/calc.py"))
PY
      - name: Run unit tests
        env:
          PYTHONPATH: src
        run: |
          pytest tests/unit -q
